# Generated by Django 3.1.5 on 2021-04-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrelinfo',
            old_name='combinationofprimary_and_highlight_color',
            new_name='combinationofprimaryandhighlightcolor',
        ),
    ]
