# Generated by Django 3.1.5 on 2021-04-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210410_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrelinfo',
            old_name='abovegroundsighter_measurement',
            new_name='abovegroundsightermeasurement',
        ),
        migrations.RenameField(
            model_name='squirrelinfo',
            old_name='other_activities',
            new_name='otheractivities',
        ),
    ]
