from django.db import models


class Squirrelinfo(models.Model):
    x = models.FloatField(blank = True, null = True)
    y = models.FloatField(blank = True, null = True)
    uniquesquirrelid = models.CharField(max_length = 200, blank = True, null = True)
    hectare = models.CharField(max_length = 200, blank = True, null = True)
    shift = models.CharField(max_length = 200, blank = True, null = True)
    date = models.CharField(max_length = 200, blank = True, null = True)
    hectaresquirrelnumber = models.CharField(max_length = 200, blank = True, null = True)
    age = models.CharField(max_length = 200, blank = True, null = True)
    primaryfurcolor = models.CharField(max_length = 200, blank = True, null = True)
    highlightfurcolor = models.CharField(max_length = 200, blank = True, null = True)
    combinationofprimaryandhighlightcolor = models.CharField(max_length = 200, blank = True, null = True)
    colornotes = models.CharField(max_length = 200, blank = True, null = True)
    location = models.CharField(max_length = 200, blank = True, null = True)
    abovegroundsightermeasurement = models.CharField(max_length = 200, blank = True, null = True)
    specificlocation = models.CharField(max_length = 200, blank = True, null = True)
    running = models.CharField(max_length = 200, blank = True, null = True)
    chasing = models.CharField(max_length = 200, blank = True, null = True)
    climbing = models.CharField(max_length = 200, blank = True, null = True)
    eating = models.CharField(max_length = 200, blank = True, null = True)
    foraging = models.CharField(max_length = 200, blank = True, null = True)
    otheractivities = models.CharField(max_length = 200, blank = True, null = True)
    kuks = models.CharField(max_length = 200, blank = True, null = True)
    quaas = models.CharField(max_length = 200, blank = True, null = True)
    moans = models.CharField(max_length = 200, blank = True, null = True)
    tailflags = models.CharField(max_length = 200, blank = True, null = True)
    tailtwitches = models.CharField(max_length = 200, blank = True, null = True)
    approaches = models.CharField(max_length = 200, blank = True, null = True)
    indifferent = models.CharField(max_length = 200, blank = True, null = True)
    runsfrom = models.CharField(max_length = 200, blank = True, null = True)
    otherinteractions = models.CharField(max_length = 200, blank = True, null = True)
    latlong = models.CharField(max_length = 200, blank = True, null = True)
